VERBOSE_DRIVER_ERRORS = False

class DriverSupportError(ImportError):
	pass

class DriverError(Exception):
	def __str__(self):
		return '\n'.join(map(str, self.args))

def check_driver_error(error, msg = '', exit = False):
	if error:
		exc = DriverError(CUresultCodes[error], msg)
		if exit:
			print(exc)
			sys.exit(1)
		else:
			raise exc

CUresultCodes = {
  0:"CUDA_SUCCESS",
  1:"CUDA_ERROR_INVALID_VALUE",
  2:"CUDA_ERROR_OUT_OF_MEMORY",
  3:"CUDA_ERROR_NOT_INITIALIZED",
  4:"CUDA_ERROR_DEINITIALIZED",
  5:"CUDA_ERROR_PROFILER_DISABLED",
  6:"CUDA_ERROR_PROFILER_NOT_INITIALIZED",
  7:"CUDA_ERROR_PROFILER_ALREADY_STARTED",
  8:"CUDA_ERROR_PROFILER_ALREADY_STOPPED",
 34:"CUDA_ERROR_STUB_LIBRARY",
100:"CUDA_ERROR_NO_DEVICE",
101:"CUDA_ERROR_INVALID_DEVICE",
102:"CUDA_ERROR_DEVICE_NOT_LICENSED",
200:"CUDA_ERROR_INVALID_IMAGE",
201:"CUDA_ERROR_INVALID_CONTEXT",
202:"CUDA_ERROR_CONTEXT_ALREADY_CURRENT",
205:"CUDA_ERROR_MAP_FAILED",
206:"CUDA_ERROR_UNMAP_FAILED",
207:"CUDA_ERROR_ARRAY_IS_MAPPED",
208:"CUDA_ERROR_ALREADY_MAPPED",
209:"CUDA_ERROR_NO_BINARY_FOR_GPU",
210:"CUDA_ERROR_ALREADY_ACQUIRED",
211:"CUDA_ERROR_NOT_MAPPED",
212:"CUDA_ERROR_NOT_MAPPED_AS_ARRAY",
213:"CUDA_ERROR_NOT_MAPPED_AS_POINTER",
214:"CUDA_ERROR_ECC_UNCORRECTABLE",
215:"CUDA_ERROR_UNSUPPORTED_LIMIT",
216:"CUDA_ERROR_CONTEXT_ALREADY_IN_USE",
217:"CUDA_ERROR_PEER_ACCESS_UNSUPPORTED",
218:"CUDA_ERROR_INVALID_PTX",
219:"CUDA_ERROR_INVALID_GRAPHICS_CONTEXT",
220:"CUDA_ERROR_NVLINK_UNCORRECTABLE",
221:"CUDA_ERROR_JIT_COMPILER_NOT_FOUND",
222:"CUDA_ERROR_UNSUPPORTED_PTX_VERSION",
223:"CUDA_ERROR_JIT_COMPILATION_DISABLED",
300:"CUDA_ERROR_INVALID_SOURCE",
301:"CUDA_ERROR_FILE_NOT_FOUND",
302:"CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND",
303:"CUDA_ERROR_SHARED_OBJECT_INIT_FAILED",
304:"CUDA_ERROR_OPERATING_SYSTEM",
400:"CUDA_ERROR_INVALID_HANDLE",
401:"CUDA_ERROR_ILLEGAL_STATE",
500:"CUDA_ERROR_NOT_FOUND",
600:"CUDA_ERROR_NOT_READY",
700:"CUDA_ERROR_ILLEGAL_ADDRESS",
701:"CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES",
702:"CUDA_ERROR_LAUNCH_TIMEOUT",
703:"CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING",
704:"CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED",
705:"CUDA_ERROR_PEER_ACCESS_NOT_ENABLED",
708:"CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE",
709:"CUDA_ERROR_CONTEXT_IS_DESTROYED",
710:"CUDA_ERROR_ASSERT",
711:"CUDA_ERROR_TOO_MANY_PEERS",
712:"CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED",
713:"CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED",
714:"CUDA_ERROR_HARDWARE_STACK_ERROR",
715:"CUDA_ERROR_ILLEGAL_INSTRUCTION",
716:"CUDA_ERROR_MISALIGNED_ADDRESS",
717:"CUDA_ERROR_INVALID_ADDRESS_SPACE",
718:"CUDA_ERROR_INVALID_PC",
719:"CUDA_ERROR_LAUNCH_FAILED",
720:"CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE",
800:"CUDA_ERROR_NOT_PERMITTED",
801:"CUDA_ERROR_NOT_SUPPORTED",
802:"CUDA_ERROR_SYSTEM_NOT_READY",
803:"CUDA_ERROR_SYSTEM_DRIVER_MISMATCH",
804:"CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE",
900:"CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED",
901:"CUDA_ERROR_STREAM_CAPTURE_INVALIDATED",
902:"CUDA_ERROR_STREAM_CAPTURE_MERGE",
903:"CUDA_ERROR_STREAM_CAPTURE_UNMATCHED",
904:"CUDA_ERROR_STREAM_CAPTURE_UNJOINED",
905:"CUDA_ERROR_STREAM_CAPTURE_ISOLATION",
906:"CUDA_ERROR_STREAM_CAPTURE_IMPLICIT",
907:"CUDA_ERROR_CAPTURED_EVENT",
908:"CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD",
909:"CUDA_ERROR_TIMEOUT",
910:"CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE",
999:"CUDA_ERROR_UNKNOWN"
}
